[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sold"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "tensorboardx",
    "torch",
    "hydra-core",
]
