defaults:
  - hydra: default

checkpoint_path: "/home/user/mosbach/PycharmProjects/sold/checkpoints/sold/reach_red/"  # Can be one checkpoint or a directory of checkpoints.
experiment: "my_experiment"
eval_episodes: 5
seed: 42

env:
  _target_: sold.envs.make_env
  suite: "mof"  # Should be "mof", "gym", or "dmcontrol".
  name: ReachRed_0to4Distractors_Dense-v1
  image_size: [ 64, 64 ]
  max_episode_steps: 50
  action_repeat: 2