model:
  _target_: sold.training.train_sold.SOLDTrainer

  collect_interval: 10
  learning_rate: 0.0001

  env:
    _target_: sold.envs.load_env
    suite: "mof"  # Should be "mof", "gym", or "dmc".
    name: ReachRed_0to4Distractors_Dense-v1
    image_size: [ 64, 64 ]
    max_episode_steps: 50
    action_repeat: 2

  savi:
    _target_: sold.training.train_savi.load_savi
    checkpoint_path: /home/user/mosbach/PycharmProjects/sold/experiments/savi/reach_red_3/2024-10-25_15-21-30/lightning_logs/version_0/checkpoints/savi-epoch=1206-val_loss=0.000381.ckpt
    finetune:
      enable: False
      every_n_episodes: 1
      iterations: 10
      batch_size: 8
      sequence_length: 8

  savi_optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.0001  # Learning rate used to finetune the SAVi model.


  dynamics_predictor:
    _target_: sold.models.sold.dynamics.DynamicsModel
    _partial_: True
    token_dim: 256
    hidden_dim: 512
    num_layers: 4
    num_heads: 8
    residual: True
    input_buffer_size: 50

  actor:
    _target_: sold.models.sold.prediction.GaussianPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

  critic:
    _target_: sold.models.sold.prediction.TwoHotPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

  reward_predictor:
    _target_: sold.models.sold.prediction.TwoHotPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512


defaults:
  - callbacks: log_sold
  - experiment: default
  - hydra: default
  - logger: tensorboard
  - trainer: sold
