defaults:
  - callbacks: sold
  - hydra: default
  - logger: tensorboard
  - trainer: online

checkpoint: "" #"/home/user/mosbach/PycharmProjects/sold/experiments/sold/reach_red2_transformer_savi_dynamics/2024-12-03_14-40-34/logs/version_0/checkpoints/sold-steps=20000-episode=801-eval_episode_return=0.23806980748794526.ckpt"
experiment: "my_experiment"
seed: 42

model:
  _target_: sold.training.train_sold.SOLDTrainer


  train_after: 10  # Start training after 'train_after' random steps/episodes.
  update_freq: 1  # Update the models every 'update_freq' steps/episodes.
  num_updates: 10  # Number of updates to perform whenever the models are updated.
  eval_freq: 100  # Evaluate the models every 'eval_freq' steps/episodes.
  num_eval_episodes: 10  # Number of episodes to collect during evaluation.
  batch_size: 8  # Batch size for training.
  #sequence_length: 16  # Number of frames in each sequence of the batch.  -> Length of sampled sequences can be determined automatically from imagination_horizon + num_context_range[1].
  buffer_capacity: 1e6  # Maximum number of time-steps to store in the replay buffer.
  interval: "episode"  # Interval for update and eval logic. Should be "time_step" or "episode".

  learning_rate: 0.0001
  num_context: [1, 5]  # [min, max] number of context frames given to the model during dynamics learning and latent imagination.
  imagination_horizon: 15  # Number of frames to predict in imagination.
  finetune_savi: False  # Whether to finetune the SAVI model.
  return_lambda: 0.95  # Lambda used to compute bootstrapped Î»-returns.
  discount_factor: 0.96  # Discount factor used to compute returns.
  critic_ema_decay: 0.98  # Exponential moving average decay for the critic target network.

  env:
    _target_: sold.envs.make_env
    suite: "mof"  # Should be "mof", "gym", or "dmcontrol".
    name: ReachRed_0to4Distractors_Dense-v1
    image_size: [ 64, 64 ]
    max_episode_steps: 50
    action_repeat: 2

  savi:
    _target_: sold.training.train_savi.load_savi
    checkpoint_path: /home/user/mosbach/PycharmProjects/sold/checkpoints/savi/reach_red2/2024-10-25_15-21-21/lightning_logs/version_0/checkpoints/remapped.zip

  dynamics_predictor:
    #_target_: sold.modeling.sold.dynamics.make_ocvp_seq_dynamics_model
    _target_: sold.modeling.sold.savi_like_dynamics.make_transformer_savi_dynamics_model
    #_target_: sold.modeling.sold.iris_dynamics.IRISDynamicsPredictor
    _partial_: True
    token_dim: 256
    hidden_dim: 512
    num_layers: 4
    num_heads: 8
    residual: True

  actor:
    _target_: sold.modeling.sold.prediction.GaussianPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

  critic:
    _target_: sold.modeling.sold.prediction.TwoHotPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

  reward_predictor:
    _target_: sold.modeling.sold.prediction.TwoHotPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512


logger:
  tensorboard:
    step_name: "current_time_step"
