model:
  _target_: sold.training.train_sold.SOLDTrainer

  learning_rate: 0.0001
  num_context: 1  # Number of context frames.
  imagination_horizon: 15  # Number of frames to predict in imagination.
  finetune_savi: True  # Whether to finetune the SAVI model.
  return_lambda: 0.95  # Lambda used to compute bootstrapped Î»-returns.
  discount_factor: 0.96  # Discount factor used to compute returns.
  critic_ema_decay: 0.98  # Exponential moving average decay for the critic target network.

  env:
    _target_: sold.envs.make_env
    suite: "mof"  # Should be "mof", "gym", or "dmc".
    name: ReachRed_0to4Distractors_Dense-v1
    image_size: [ 64, 64 ]
    max_episode_steps: 50
    action_repeat: 2

  savi:
    _target_: sold.training.train_savi.load_savi
    checkpoint_path: /home/user/mosbach/PycharmProjects/sold/checkpoints/savi/reach_red/2024-10-25_15-21-30/logs/version_0/checkpoints/savi-epoch=800-val_loss=0.000501.ckpt

  dynamics_predictor:
    _target_: sold.modeling.sold.dynamics.OCVPSeqDynamicsModel
    _partial_: True
    token_dim: 256
    hidden_dim: 512
    num_layers: 4
    num_heads: 8
    residual: True
    input_buffer_size: 50

  actor:
    _target_: sold.modeling.sold.prediction.GaussianPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

  critic:
    _target_: sold.modeling.sold.prediction.TwoHotPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

  reward_predictor:
    _target_: sold.modeling.sold.prediction.TwoHotPredictor
    _partial_: True
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512


logger:
  tensorboard:
    step_name: "current_step"


defaults:
  - callbacks: sold
  - experiment: default
  - hydra: default
  - logger: tensorboard
  - trainer: online
