model:
  _target_: sold.sold.model.SOLD

  env:
    _target_: sold.envs.load.load_env
    suite: "mof"  # Should be "mof", "gym", or "dmc".
    name: PushRed_0to4Distractors_Dense-v1
    image_size: [ 64, 64 ]
    max_episode_steps: 100
    action_repeat: 2

  savi:
    _target_: sold.savi.model.SAVi.load_from_checkpoint
    checkpoint_path: /home/user/mosbach/PycharmProjects/sold/experiments/savi/actual_savi/2024-10-22_17-16-06/tensorboard/lightning_logs/version_0/checkpoints/savi-epoch=00-val_loss=0.052440.ckpt

  actor:
    _target_: sold.sold.actor.Actor
    _partial_: True  # Action-dimension is filled in from env.
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

  critic:
    _target_: sold.sold.critic.Critic
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

  reward_predictor:
    _target_: sold.sold.reward_predictor.RewardPredictor
    token_dim: 256
    num_heads: 8
    num_layers: 4
    hidden_dim: 512

defaults:
  - callbacks: default
  - experiment: default
  - hydra: default
  - logger: tensorboard
  - trainer: default
